version: '3'
services:
  server:
    build: ./docker/server
    container_name: 'webpagetest_server'
    ports:
      - '80:80'
    volumes:
      - /tmp/wpt_results/results:/var/www/html/results
      - /tmp/wpt_results/logs:/var/www/html/logs
  agent:
    build: ./docker/agent
    container_name: 'webpagetest_agent'
    network_mode: "host"
    environment:
      - SERVER_URL=http://localhost:80/work/
      - LOCATION=Test
#   cron:
#     image: alpine:3.16.0
#     container_name: 'cron_app'
#     command: >
#       sh -c "
#       echo '1 1 * * * rm -rf /var/www/html/results/* ' > /etc/crontabs/root
#       && crond -f"
#     volumes:
#       - results:/var/www/html/results
#       - logs:/var/www/html/results
#     depends_on:
#       - server
# volumes:
#   data:
